version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

parameters:
  test:
    type: boolean
    default: false
    description: "Whether this is test pipeline."

jobs:
  success:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Success
          command: echo "Success!"


workflows:
  lint-pack:
    when:
      equal: [false, << pipeline.parameters.test >>]
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: circleback-orb
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
  test:
    when:
      equal: [true, << pipeline.parameters.test >>]
    jobs:
      - success:
          filters: *filters
